bottradehoon/hoon/urls.py
from os import name
from django.urls import path, re_path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'hoon'
urlpatterns = [
    path('', index),
    path('equity/<str:room_name>/', equity, name='equity'),
    path('portfolio', portfolio),
    path('logout', logout_view, name='logout'),
    path('login_form', login_view, name='login_view'),
    # re_path(r'login', login_user),
]

bottradehoon/space/urls.py
from django.urls import path, re_path, include
from .views import *
from hoon.views import logout_view, login_user
from django.contrib.auth import views as auth_views

app_name = 'space'

urlpatterns = [
    path('', index, name='main'),
    path('equity/<str:room_name>/', equity, name='trade'),
    # path('portfolio', portfolio, name='portfolio'),
    path('logout', logout_view, name='logout'),
    path('login_form', login_form, name='login_form'),
    re_path(r'login', login_user),

    path('api', api_list, name='api-list'),
    path('api/portfolio', api_portfolio, name='api-portfolio'),
    path('api/account', api_account, name='api-account'),
    path('api/get_orders', api_list_order, name='api-get-orders'),
    re_path(r'api/get_profit/(?:page-(?P<page_number>\d+)/)?$', api_profit, name='api-get-profit'),
    path('api/condition/<str:symbol>', api_list_order, name='api-get-orders'),
]

bottradehoon/space/models.py
from django.db import models

# Create your models here.

bottradehoon/space/views.py
from asyncio import Task
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from pprint import pprint
from django.contrib import messages
import logging
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import subprocess
from pathlib import Path
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import api_view
import datetime
from hoon.models import Condition, Result
from hoon.settrade_api import equity as eq
from hoon.settrade_api import trade
from hoon.serializers import ConditionSerializer

# Create your views here.
# Create instance
logger = logging.getLogger('hoon')
cwd = Path(__file__).resolve().parent.parent.parent
version = subprocess.check_output(['git', 'describe'], cwd=cwd).strip()
version = version.decode("utf-8")
per_page = 20


@login_required
def index(request):
    # Query Data From Model
    data = Condition.objects.all()
    # order_status = trade().order_status('GP25BL6BT')
    # pprint(order_status)
    return render(request, 'stock_space/index.html', {'posts': data, 'room_name': 'home'})


@login_required
def portfolio(request):
    trade().session_check_or_login("portfolio")
    portfolio = eq.get_portfolio()
    logger.info(portfolio)
    return render(request, 'stock_space/index.html', {'version': version, 'posts': portfolio['data']})


@login_required
def equity(request, room_name):
    logger.debug(room_name)
    # Query Data From Model
    data = Condition.objects.all()
    return render(request, 'stock_space/index.html', {'version': version, 'posts': data, 'room_name': room_name})


def logout_view(request):
    logout(request)
    return redirect('/stock_space/index.html')


def login_page(request):
    return render(request, 'stock_space/login.html')


def login_form(request):
    # print(request.GET)
    next = request.GET.get('next')
    return render(request, 'stock_space/login.html', {'next': next})


def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    next = request.GET.get('next', '')
    if user is not None:
        # Log a user in
        login(request, user)
        # messages.success(request, 'Your password was updated successfully!')
    else:
        # return HttpResponse("Incorrect user<br><a href=""/"">Get back to home page</a>")
        messages.warning(request, 'The username or password is incorrect!')
    return redirect(next)


def get_profit():
    today = datetime.date.today()
    list_monthly = []
    list_daily = []
    daily_sum_profit = []
    dialy_sum_loss = []
    total = {}

    symbols = Condition.objects.only('symbol')

    res = Result.objects.all()

    try:
        first_year = res[0].created_at.year
    except IndexError:
        return
    except AttributeError:
        first_year = today.year

    for y in range(today.year, int(first_year)-1, -1):
        # Months
        for m in range(1,13):

            month_profit = 0
            month_loss = 0
            name_y = datetime.datetime(y, m, 1)
            name_y = name_y.strftime("%b %y")

            # Calculate 31 Days
            for d in range(1, 32):
                # Calculate 1 Day
                day_profit = 0
                day_loss = 0

                days = Result.objects.filter(created_at__day=d,
                                             created_at__month=m,
                                             created_at__year=y,)

                if days:
                    # Sum 1 day
                    for sym in symbols:
                        day = days.filter(symbol=sym)
                        if day:
                            realize = day[len(
                                day)-1].json_data['portfolio']['realize_profit']
                            if realize > 0:
                                # Profit
                                day_profit += realize
                            else:
                                day_loss += realize

                    name_d = datetime.datetime(y, m, d)
                    name_d = name_d.strftime("%d %b %y")

                    daily_sum_profit.append(day_profit)
                    dialy_sum_loss.append(day_loss)
                    list_daily.append({name_d: [day_profit, day_loss]})

                # Sum 1 Month
                month_profit += day_profit
                month_loss += day_loss

            # Calculate 1 Mounth
            if month_profit !=0 and month_loss !=0:
                list_monthly.append({name_y: [month_profit, month_loss]})

    page_monthly = Paginator(list_monthly, per_page)
    page_daily = Paginator(list_daily, per_page)

    total_profit = sum([v for v in daily_sum_profit])
    total_loss = sum([v for v in dialy_sum_loss])

    total['profit'] = total_profit
    total['loss'] = total_loss
    total['nett'] = total_profit + total_loss

    return total, page_daily, page_monthly


class ConditionViewSet(viewsets.ModelViewSet):
    queryset = Condition.objects.all()
    serializer_class = ConditionSerializer


@api_view(['GET'])
def api_list(request):
    url = request.build_absolute_uri()
    api_urls = {
        'Portfolio': url + '/portfolio'
    }
    return Response(api_urls)


@api_view(['GET'])
def api_portfolio(request):
    trade().session_check_or_login("portfolio")
    portfolio = eq.get_portfolio()
    return Response(portfolio['data'])


@api_view(['GET'])
def api_account(request):
    trade().session_check_or_login("account")
    account = eq.get_account_info()
    return Response(account)


@api_view(['GET'])
def api_list_order(request):
    trade().session_check_or_login("list_order")
    orders = eq.get_orders()
    return Response(orders['data'])


@api_view(['GET'])
def api_profit(request):
    page_obj_daily = {}
    page_obj_monthly = {}
    page_number = request.GET.get('page')
    total, page_daily, page_monthly = get_profit()

    if int(page_number) <= page_daily.num_pages:
        for p in page_daily.page(page_number).object_list:
            key = list(p)
            page_obj_daily[key[0]] = list(p.values())[0]

    if int(page_number) <= page_monthly.num_pages:
        for p in page_monthly.page(page_number).object_list:
            key = list(p)
            page_obj_monthly[key[0]] = list(p.values())[0]

    page_obj = {'daily': {'data': page_obj_daily},
                'monthly': {'data': page_obj_monthly}, 'total': total, 'per_page': per_page}

    page_obj['daily']['num_pages'] = page_daily.num_pages
    page_obj['daily']['count'] = page_daily.count
    page_obj['monthly']['num_pages'] = page_monthly.num_pages
    page_obj['monthly']['count'] = page_monthly.count

    return Response(page_obj)

# https://stackoverflow.com/questions/16750464/django-redirect-after-login-not-working-next-not-posting

bottradehoon/space/templates/stock_space/confirm-logout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Radiplus</title>
    <!-- Icon-->
    <link href="../../assets/images/access/favicon.ico" rel="shortcut icon">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <!-- style-->
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="stylesheet" href="../../assets/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
      var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
      var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
          return new bootstrap.Popover(popoverTriggerEl)
      })
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="../../assets/js/common.js"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="content">
        <div class="nav nav-tabs navbar"><a href="#home" data-bs-toggle="tab" class="active"><i class="fas fa-home"></i><span>Home</span></a><a href="#trade" data-bs-toggle="tab"><i class="fas fa-exchange-alt"></i><span>Trade </span></a><a href="#portfolio" data-bs-toggle="tab"><i class="fas fa-briefcase"></i><span>Portfolio</span></a><a href="#login" data-bs-toggle="tab"><i class="fas fa-sign-in-alt"></i><span>Logout</span></a></div>
        <div class="tab-content">
          <div id="home" class="tab-pane active">
            <div class="nav-select">
              <select>
                <option>AOT - บริษัท ท่าอากาศยานไทย จำกัด (มหาชน)</option>
              </select>
              <!--.dropdown
              button.btn.dropdown-toggle(type="button" data-bs-toggle='dropdown')
                  span AOT
              .dropdown-menu
                  a.dropdown-item
                      | AOT
                  a.dropdown-item
                      | ABC
                  a.dropdown-item
              -->
            </div>
            <div class="bar-name">
              <div class="media">
                <div class="float-left">
                  <h1>AOT </h1>
                </div>
                <div class="media-body">
                  <div class="price color-success">180.75 <span>THB</span></div>
                  <div class="change">Change (+0.7%)</div>
                  <div class="latest-info">ข้อมูลล่าสุด: 2021/12/18 22:21:39</div>
                </div>
              </div>
            </div>
            <hr>
            <div class="bar-price">
              <div class="form-group">
                <label>ราคาสูงสุด</label><span>194.50<span>THB</span></span>
              </div>
              <div class="form-group">
                <label>ราคาต่ำสุด</label><span>157.50<span>THB</span></span>
              </div>
              <div class="form-group">
                <label>ราคาเริ่มต้น</label><span>166.25<span>THB</span></span>
              </div>
            </div>
            <section>
              <h3 class="title">ประวัติการทำรายการ</h3>
              <div class="table-responsive table-column-fix">
                <table style="min-width: 746px;" class="table">
                  <colgroup>
                    <col style="width: 46px;">
                    <col style="width: 70px;">
                    <col style="width: 120px;">
                    <col style="width: 120px;">
                    <col style="width: 120px;">
                    <col style="width: 100px;">
                    <col style="width: 100px;">
                    <col style="width: 70px;">
                  </colgroup>
                  <thead>
                    <tr>
                      <th style="left: 0px;" class="sticky text-center">No.</th>
                      <th style="left: 46px;" class="sticky-left">Symbol</th>
                      <th>Time</th>
                      <th>Side</th>
                      <th>Volume</th>
                      <th>Matched</th>
                      <th>Banlace</th>
                      <th style="right: 0;" class="sticky-right">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td style="left: 0;" class="sticky text-center">1</td>
                      <td style="left: 46px;" class="sticky-left">AOT</td>
                      <td>-</td>
                      <td>-</td>
                      <td>100,000.00</td>
                      <td>Matched</td>
                      <td>Banlace</td>
                      <td style="right: 0;" class="sticky-right">
                        <div class="status"><i class="icon-dot-status yellow"></i><span>Draft</span></div>
                      </td>
                    </tr>
                    <tr>
                      <td style="left: 0;" class="sticky text-center">2</td>
                      <td style="left: 46px;" class="sticky-left">ABC</td>
                      <td>-</td>
                      <td>-</td>
                      <td>100,000.00</td>
                      <td>Matched</td>
                      <td>Banlace</td>
                      <td style="right: 0;" class="sticky-right">
                        <div class="status"><i class="icon-dot-status yellow"></i><span>Draft</span></div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>
          </div>
          <div id="trade" class="tab-pane">
            <div class="nav-select">
              <select>
                <option>AOT - บริษัท ท่าอากาศยานไทย จำกัด (มหาชน)</option>
              </select>
              <!--.dropdown
              button.btn.dropdown-toggle(type="button" data-bs-toggle='dropdown')
                  span AOT
              .dropdown-menu
                  a.dropdown-item
                      | AOT
                  a.dropdown-item
                      | ABC
                  a.dropdown-item
              -->
            </div>
            <div class="bar-name">
              <div class="media">
                <div class="float-left">
                  <h1>AOT </h1>
                </div>
                <div class="media-body">
                  <div class="price color-success">180.75 <span>THB</span></div>
                  <div class="change">Change (+0.7%)</div>
                  <div class="latest-info">ข้อมูลล่าสุด: 2021/12/18 22:21:39</div>
                </div>
              </div>
            </div>
            <hr>
            <div class="bar-price">
              <div class="form-group">
                <label>ราคาสูงสุด</label><span>194.50<span>THB</span></span>
              </div>
              <div class="form-group">
                <label>ราคาต่ำสุด</label><span>157.50<span>THB</span></span>
              </div>
              <div class="form-group">
                <label>ราคาเริ่มต้น</label><span>166.25<span>THB</span></span>
              </div>
            </div>
            <div class="nav nav-tabs nav-second"><a href="#account" data-bs-toggle="tab" class="active">Account Information</a><a href="#condition" data-bs-toggle="tab">Trade</a></div>
            <div class="tab-content">
              <div id="account" class="tab-pane active">
                <div class="form-group">
                  <label>Credit Limit</label><span>100,000,000<span>THB</span></span>
                </div>
                <div class="form-group">
                  <label>Line Available</label><span>100,000<span>THB</span></span>
                </div>
                <div class="form-group">
                  <label>Cash Balance</label><span>100,000<span>THB</span></span>
                </div>
                <div class="form-group">
                  <label>Can Buy / Sell</label><span>100,000<span>THB</span></span>
                </div>
                <div class="form-group">
                  <label>Buy ( Volume / Estimate Amount )</label><span>True / True</span>
                </div>
                <div class="form-group">
                  <label>Sell ( Volume / Profit )</label><span>0 / 0<span>THB</span></span>
                </div>
                <div class="form-group">
                  <label>Status</label><span>-</span>
                </div>
                <div class="form-action">
                  <div class="row">
                    <div class="col-6">
                      <button type="button" class="btn btn-block btn-outline success">ซื้อ</button>
                    </div>
                    <div class="col-6">
                      <button type="button" class="btn btn-block btn-outline danger">ขาย</button>
                    </div>
                  </div>
                </div>
              </div>
              <div id="condition" class="tab-pane">
                <div class="content-group">
                  <h3 class="title">Trade Condition<a href=""><i class="fas fa-cog"></i>ตั้งค่าเทรด</a></h3>
                  <div class="form-group">
                    <label>Credit Limit</label><span>100,000,000<span>THB</span></span>
                  </div>
                  <div class="form-group">
                    <label>Line Available</label><span>100,000<span>THB</span></span>
                  </div>
                  <div class="form-group">
                    <label>Cash Balance</label><span>100,000<span>THB</span></span>
                  </div>
                  <div class="form-group">
                    <label>Can Buy / Sell</label><span>100,000<span>THB</span></span>
                  </div>
                  <div class="form-group">
                    <label>Buy ( Volume / Estimate Amount )</label><span>True / True</span>
                  </div>
                  <div class="form-group">
                    <label>Sell ( Volume / Profit )</label><span>0 / 0<span>THB</span></span>
                  </div>
                </div>
                <div class="content-group">
                  <h3 class="title">Robot Trade</h3>
                  <div class="form-action">
                    <div class="row">
                      <div class="col-6">
                        <button type="button" class="btn btn-block btn-outline success">เทรด</button>
                      </div>
                      <div class="col-6">
                        <button type="button" class="btn btn-block btn-outline danger">รีเซ็ตเทรด</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="portfolio" class="tab-pane">
            <section>
              <h3 class="title">Portfolio</h3>
              <div class="table-responsive table-column-fix">
                <table style="min-width: 800px;" class="table">
                  <colgroup>
                    <col style="width: 70px;">
                    <col style="width: 130px;">
                    <col style="width: 130px;">
                    <col style="width: 130px;">
                    <col style="width: 130px;">
                    <col style="width: 130px;">
                    <col style="width: 80px;">
                  </colgroup>
                  <thead>
                    <tr>
                      <th style="left: 0;" class="sticky-left">Symbol</th>
                      <th>Actual Vol</th>
                      <th>Market Price</th>
                      <th>Amount</th>
                      <th>Market Value</th>
                      <th>Profit</th>
                      <th>%Profit</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td style="left: 0;" class="sticky-left">AOT</td>
                      <td class="color-warning">150,000.00</td>
                      <td>200,000.00</td>
                      <td>250,000.00</td>
                      <td>Market Value</td>
                      <td class="color-danger">54,120.44</td>
                      <td class="color-danger">-24%</td>
                    </tr>
                    <tr>
                      <td style="left: 0;" class="sticky-left">ABC</td>
                      <td class="color-warning">150,000.00</td>
                      <td>291,000.00</td>
                      <td>209,000.00</td>
                      <td>Market Value</td>
                      <td class="color-success">454,980.09</td>
                      <td class="color-success">220%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal-->
  </body>
</html>

bottradehoon/space/templates/stock_space/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Radiplus</title>
        <!-- Icon-->
        <link href="{% static 'assets/images/access/favicon.ico' %}" rel="shortcut icon">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <!-- style-->
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript">
            var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
            var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
                return new bootstrap.Popover(popoverTriggerEl)
            })
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="{% static 'assets/js/common.js' %}"></script>
    </head>

    {% block content %}

    {% endblock %}

</html>

bottradehoon/space/templates/stock_space/login.html
{% extends 'stock_space/layout.html' %}

{% block content %}

<body class="login">
  <div class="bg"></div>
  <div class="container-fluid">
    <div class="content">
      {% if next %}
      <form action="{% url 'space:login_form' %}/login?next={{next}}" method="post">
      {% endif %}
        {% csrf_token %}
        <div class="login-form">
          <div>
            <div class="title-header"><span>B</span><span>o</span><span>t</span><br>trade<br>hoon</div>
            <div class="form-group">
              <label>Username</label>
              <input type="text" placeholder="Username" class="form-control" name="username">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" type="text" placeholder="Password" class="form-control" name="password">
            </div>
            <div class="form-action">
              <button class="btn btn-block btn-primary" type="submit">Login</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- Modal-->
</body>

{% endblock %}